version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: suivi_candidature_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: suivi_candidature_db
            MYSQL_USER: suivi_candidature_user
            MYSQL_PASSWORD: 123456789
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - suivi_candidature_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 3s
            retries: 10

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: suivi_candidature_api
        restart: unless-stopped
        volumes:
            - /var/www/html
            - storage_data:/var/www/html/storage/app/public
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=suivi_candidature_db
            - DB_USERNAME=suivi_candidature_user
            - DB_PASSWORD=123456789
            - APP_ENV=production
            - APP_DEBUG=false
        entrypoint: >
            sh -c "
            php artisan config:cache &&
            php artisan route:cache &&
            php artisan view:cache &&
            php artisan storage:link --force &&
            php artisan migrate --force &&
            apache2-foreground
            "
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - suivi_candidature_network

    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        container_name: react_web
        restart: unless-stopped
        volumes:
            - ./web:/app
            - /app/node_modules
        environment:
            - VITE_API_URL=http://localhost/api
        networks:
            - suivi_candidature_network

    nginx:
        image: nginx:alpine
        container_name: suivi_candidature_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - storage_data:/var/www/storage:ro
        depends_on:
            - api
            - web
        networks:
            - suivi_candidature_network

volumes:
    mysql_data:
    storage_data:

networks:
    suivi_candidature_network:
        driver: bridge