version: '3.8'

services:
    # MySQL Database
    mysql:
        image: mysql:8.0
        container_name: suivi_candidature_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: suivi_candidature_db
            MYSQL_USER: suivi_candidature_user
            MYSQL_PASSWORD: 123456789
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - suivi_candidature_network

    # suivi_candidature API (Laravel + Apache)
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: suivi_candidature_api
        restart: unless-stopped
        volumes:
            - ./api:/var/www/html
            # important : on garde vendor et node_modules dans le container
            - /var/www/html/vendor
            - /var/www/html/node_modules
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=suivi_candidature_db
            - DB_USERNAME=suivi_candidature_user
            - DB_PASSWORD=123456789
        # Retiré le port 8000 car nginx va gérer le proxy
        command: >
            sh -c "php artisan config:publish cors --force &&
                   php artisan key:generate --no-interaction --force &&
                   php artisan migrate --force &&
                   chown -R www-data:www-data storage bootstrap/cache &&
                   chmod -R 775 storage bootstrap/cache &&
                   apache2-foreground"
        depends_on:
            - mysql
        networks:
            - suivi_candidature_network

    # React Web App (Vite)
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        container_name: react_web
        restart: unless-stopped
        volumes:
            - ./web:/app
            - /app/node_modules
        environment:
            # Changé l'URL de l'API pour passer par nginx
            - REACT_APP_API_URL=http://localhost/api
        depends_on:
            - api
        networks:
            - suivi_candidature_network

    # Nginx Reverse Proxy
    nginx:
        image: nginx:alpine
        container_name: suivi_candidature_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api
            - web
        networks:
            - suivi_candidature_network

volumes:
    mysql_data:

networks:
    suivi_candidature_network:
        driver: bridge